#!/bin/bash

# Commands to run on DigitalOcean server console
# Copy and paste these commands one by one on the server

echo "🚀 DigitalOcean Deployment Commands"
echo "=================================="
echo ""
echo "1. Navigate to project directory:"
echo "cd /var/www/campus-digitale-fad"
echo ""
echo "2. Pull latest changes:"
echo "git pull origin main"
echo ""
echo "3. Install/update Composer dependencies:"
echo "composer install --no-dev --optimize-autoloader"
echo ""
echo "4. Install/update NPM dependencies:"
echo "npm ci"
echo ""
echo "5. Build frontend assets:"
echo "npm run build"
echo ""
echo "6. Run database migrations:"
echo "php artisan migrate --force"
echo ""
echo "7. Clear application cache:"
echo "php artisan config:clear"
echo "php artisan cache:clear"
echo "php artisan route:clear"
echo "php artisan view:clear"
echo ""
echo "8. Optimize application:"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo "php artisan view:cache"
echo ""
echo "9. Set proper permissions:"
echo "chown -R www-data:www-data storage bootstrap/cache"
echo "chmod -R 775 storage bootstrap/cache"
echo ""
echo "10. Restart services:"
echo "systemctl reload nginx"
echo "systemctl restart php8.2-fpm"
echo ""
echo "✅ Deployment completed!"
echo "🌐 Your application is live at: https://fad.campusdigitale.online"
